name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar SDK de Android
        uses: android-actions/setup-android@v3
      - name: Instalar dependencias
        run: ./gradlew dependencies
      - name: Compilar el proyecto
        run: ./gradlew assembleDebug
      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: isr-calculadora-apk
          path: app/build/outputs/apk/debug/app-debug.apk
