name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos de ejecuci√≥n a gradlew
        run: chmod +x gradlew
      
      - name: Configurar SDK de Android
        run: |
          export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0"
      
      - name: Compilar proyecto Android
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: calculadora-isr-apk
          path: app/build/outputs/apk/debug/app-debug.apk
