name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos de ejecución a gradlew
        run: chmod +x gradlew
      
      - name: Configurar SDK de Android con versión específica
        uses: android-actions/setup-android@v3
        with:
          sdk-version: "33"
          build-tools-version: "33.0.0"
          cmdline-tools-version: "8.0"
      
      - name: Instalar dependencias
        run: ./gradlew dependencies --stacktrace
      
      - name: Compilar el proyecto
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: isr-calculadora-apk
          path: app/build/outputs/apk/debug/app-debug.apk
