name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos de ejecuciÃ³n a gradlew
        run: chmod +x gradlew
      
      - name: Instalar herramientas de Android
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip -d cmdline-tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
      
      - name: Instalar dependencias
        run: ./gradlew dependencies --stacktrace
      
      - name: Compilar el proyecto
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: isr-calculadora-apk
          path: app/build/outputs/apk/debug/app-debug.apk
