name: Build Android APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Dar permisos de ejecuciÃ³n a gradlew
        run: chmod +x gradlew
      
      - name: Instalar SDK de Android manualmente
        run: |
          sudo apt-get update
          sudo apt-get install -y android-sdk
          echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/lib/android-sdk/tools:/usr/lib/android-sdk/platform-tools" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
      
      - name: Instalar dependencias
        run: ./gradlew dependencies --stacktrace
      
      - name: Compilar el proyecto
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Subir APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: isr-calculadora-apk
          path: app/build/outputs/apk/debug/app-debug.apk
